Completed the basic requirement-Kenneth. W
Kenneth-Y-Wang/c0821-code-solutions pull request #47
Opened 2021-09-01 16:53 UTC by Kenneth-Y-Wang

https://user-images.githubusercontent.com/88110300/131712013-69420476-dd61-4035-8687-5c1845a7b4ec.mov

2021-09-01 17:55 UTC, codingcodymiller requested changes
Good start here! A couple notes for you:

2021-09-01 17:55 UTC, codingcodymiller commented on javascript-typing-tutor/styles.css
> +}
This shouldn't be necessary. Are your space characters not showing up on the page? We should diagnose this issue so that you don't need huge spaces between your words made up of white text.

2021-09-01 17:55 UTC, codingcodymiller commented on javascript-typing-tutor/type.js
> +var $spam = document.querySelectorAll('span.letter');
This should be `$span`

2021-09-01 22:59 UTC, codingcodymiller requested changes
Just sending another review so that this doesn't show as being ready for another review yet 👍

2021-09-02 20:02 UTC, codingcodymiller requested changes
Still in progress, I see, so here's another review! You can also wait to `push` your branch until you are completely done, so I don't get these notifications 🤓

2021-09-02 21:54 UTC, codingcodymiller requested changes

2021-09-02 21:54 UTC, codingcodymiller commented on javascript-typing-tutor/type.js
> +});
There shouldn't be a need for two keydown event handlers, you should merge this with your other event handler above. I also recommend making named functions rather than anonymous functions.

2021-09-02 21:54 UTC, codingcodymiller commented on javascript-typing-tutor/styles.css
> +}
Now that this is no longer in use, you should delete it.

2021-09-03 16:14 UTC, codingcodymiller requested changes

2021-09-03 16:14 UTC, codingcodymiller commented on javascript-typing-tutor/type.js
> +  }
This looks like very similar functionality to the conditional above, can they be merged at all?

2021-09-03 20:31 UTC, Kenneth-Y-Wang commented
and I works!

2021-09-03 21:35 UTC, Kenneth-Y-Wang commented
Sorry, I meant it works

2021-09-04 00:12 UTC, codingcodymiller approved these changes
Excellent work!!

2021-09-05 01:27 UTC, merged